#!/bin/bash +vx

# To run server generated by thrift compiler
# python3 src/PythonClient.py $1 $2

# To run multiple client with list of operation, ip:port, file_name info in a file
echo "Please enter operation file full path."
read input_file

# cat $input_file | sed -e "s/:/ /" | while read ip port; do echo $ip "Hey $port"; done

cat $input_file | sed -e "s/ / /" | while read operation ip port filename;
do
  # echo "Starting client with operation $operation $ip $port $filename"
  echo "Starting client at $ip:$port ...";
  # xterm -title "Client $port" -e "python3 ./src/client.py $operation $ip $port $filename";
  python3 ./src/client.py $operation $ip $port $filename
done

echo "Finished starting clients ..."
